
#controller_frequency: 3.0
controller_frequency: 1.0 
recovery_behavior_enabled: false
clearing_rotation_allowed: false

TrajectoryPlannerROS:
  max_vel_x: 0.4 
  min_vel_x: 0.05 
  max_vel_y: 0.2  # zero for a differential drive robot
  min_vel_y: 0.05  # zero for a differential drive robot
  max_vel_theta: 0.7 
  min_vel_theta: 0.4 
  min_in_place_vel_theta: 0.5 
  max_rotational_vel: 0.8 
  min_in_place_rotational_vel: 0.5 
  escape_vel: -0.10 
  acc_lim_x: 0.1 
  acc_lim_y: 0.1 
  acc_lim_theta: 1.0 

  holonomic_robot: false
  yaw_goal_tolerance: 0.1 
  xy_goal_tolerance: 0.1 
  gdist_scale: 0.8 
  pdist_scale: 0.6 
  
  latch_xy_goal_tolerance: false 
  
  heading_lookahead: 0.3 
  heading_scoring: false 
  heading_scoring_timestep: 0.1 
  #meter_scoring: false
  meter_scoring: true 
  oscillation_reset_dist: 0.05 
  occdist_scale: 0.05 
 
  publish_cost_grid_pc: false

  sim_time: 1.7 
  sim_granularity: 0.025 
  angular_sim_granularity: 0.025 
  vx_samples: 8
  vy_samples: 8 # zero for a differential drive robot 
  vtheta_samples: 20 
  dwa: true 
  simple_attractor: false



