local_costmap:
   #global_frame: /odom
   global_frame: /odom_combined
   robot_base_frame: /base_footprint
   update_frequency: 3.0
   publish_frequency: 1.0
   static_map: false
   rolling_window: true
   width: 3.0
   height: 3.0
   resolution: 0.05 #should same as map.yaml file
   transform_tolerance: 1.0
   map_type: costmap

   #This param is in costmap_common_params.yaml
   plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}